# Menggunakan Docker Compose versi 3.7
version: '3.7'

services:
  item-app:
    # Menggunakan image dari GitHub Container Registry
    image: ghcr.io/maulanadw/item-app:v1
    # Port mapping agar bisa diakses dari port 80 di host
    ports:
      - 80:8080
    # Memastikan item-app hanya berjalan setelah item-db diluncurkan
    depends_on:
      - item-db
    # Restart policy agar container selalu restart ketika terhenti
    restart: always
      
  item-db:
    # Menggunakan image resmi MongoDB dari Docker Hub
    image: mongo:3
    # Menggunakan volume app-db untuk penyimpanan data
    volumes:
      - app-db:/data/db
    # Restart policy agar container selalu restart ketika terhenti
    restart: always

# Membuat volume bernama app-db
volumes:
  app-db:
